# -*- coding: utf-8 -*-
"""01_register_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15varczMUrG9sE4wz2vnBfavbNThdGCrR
"""

import os
import pandas as pd
import streamlit as st
import joblib
from huggingface_hub import hf_hub_download

HF_MODEL_REPO = os.environ.get("HF_MODEL_REPO", "")
MODEL_FILE = "best_model.joblib"

st.set_page_config(page_title="Visit with Us – Wellness Package Predictor", layout="centered")
st.title("Wellness Tourism Package – Purchase Prediction")

@st.cache_resource
def load_model():
    model_path = hf_hub_download(repo_id=HF_MODEL_REPO, repo_type="model", filename=MODEL_FILE)
    return joblib.load(model_path)

model = load_model()

st.subheader("Enter customer details")

# Keep fields aligned with your dataset columns (except ProdTaken)
age = st.number_input("Age", min_value=18, max_value=100, value=35)
typeofcontact = st.selectbox("TypeofContact", ["Company Invited", "Self Enquiry"])
citytier = st.selectbox("CityTier", [1, 2, 3])
duration = st.number_input("DurationOfPitch", min_value=0.0, value=10.0)
occupation = st.selectbox("Occupation", ["Salaried", "Free Lancer", "Small Business", "Large Business"])
gender = st.selectbox("Gender", ["Male", "Female"])
nop = st.number_input("NumberOfPersonVisiting", min_value=1, value=2)
followups = st.number_input("NumberOfFollowups", min_value=0.0, value=3.0)
productpitched = st.selectbox("ProductPitched", ["Basic", "Deluxe", "Standard", "Super Deluxe", "King"])
star = st.number_input("PreferredPropertyStar", min_value=1.0, max_value=5.0, value=3.0)
marital = st.selectbox("MaritalStatus", ["Single", "Married", "Divorced"])
trips = st.number_input("NumberOfTrips", min_value=0.0, value=2.0)
passport = st.selectbox("Passport", [0, 1])
pitchscore = st.selectbox("PitchSatisfactionScore", [1, 2, 3, 4, 5])
owncar = st.selectbox("OwnCar", [0, 1])
kids = st.number_input("NumberOfChildrenVisiting", min_value=0.0, value=0.0)
designation = st.selectbox("Designation", ["Executive", "Manager", "Senior Manager", "AVP", "VP"])
income = st.number_input("MonthlyIncome", min_value=0.0, value=25000.0)

row = {
    "Age": age,
    "TypeofContact": typeofcontact,
    "CityTier": citytier,
    "DurationOfPitch": duration,
    "Occupation": occupation,
    "Gender": gender,
    "NumberOfPersonVisiting": nop,
    "NumberOfFollowups": followups,
    "ProductPitched": productpitched,
    "PreferredPropertyStar": star,
    "MaritalStatus": marital,
    "NumberOfTrips": trips,
    "Passport": passport,
    "PitchSatisfactionScore": pitchscore,
    "OwnCar": owncar,
    "NumberOfChildrenVisiting": kids,
    "Designation": designation,
    "MonthlyIncome": income,
}

if st.button("Predict"):
    X = pd.DataFrame([row])
    proba = model.predict_proba(X)[:, 1][0]
    pred = int(proba >= 0.5)
    st.write("### Result")
    st.metric("Purchase Probability", f"{proba:.2%}")
    st.success("Likely to Purchase ✅" if pred == 1 else "Unlikely to Purchase ❌")
    st.caption("Tip: use probability for targeting thresholds (e.g., >0.65 = priority lead).")