# -*- coding: utf-8 -*-
"""01_register_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15varczMUrG9sE4wz2vnBfavbNThdGCrR
"""

import os
from huggingface_hub import HfApi

HF_DATASET_REPO = os.environ["HF_DATASET_REPO"]
RAW_PATH = os.environ.get("RAW_PATH", "tourism.csv")

def main():
    api = HfApi()
    api.create_repo(repo_id=HF_DATASET_REPO, repo_type="dataset", exist_ok=True)
    api.upload_file(
        path_or_fileobj=RAW_PATH,
        path_in_repo="data/tourism.csv",
        repo_id=HF_DATASET_REPO,
        repo_type="dataset",
    )
    print("✅ Uploaded raw data to HF dataset repo:", HF_DATASET_REPO)

if __name__ == "__main__":
    main()