# -*- coding: utf-8 -*-
"""01_register_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15varczMUrG9sE4wz2vnBfavbNThdGCrR
"""

import os
import pandas as pd
from sklearn.model_selection import train_test_split
from huggingface_hub import HfApi, hf_hub_download

HF_DATASET_REPO = os.environ["HF_DATASET_REPO"]
SEED = int(os.environ.get("SEED", "42"))
TEST_SIZE = float(os.environ.get("TEST_SIZE", "0.2"))

OUT_DIR = "data/processed"
TRAIN_PATH = f"{OUT_DIR}/train.csv"
TEST_PATH  = f"{OUT_DIR}/test.csv"

def clean(df: pd.DataFrame) -> pd.DataFrame:
    # Drop obvious non-feature index column if present
    if "Unnamed: 0" in df.columns:
        df = df.drop(columns=["Unnamed: 0"])

    # Remove fully empty columns (safety)
    df = df.dropna(axis=1, how="all")

    # Standardize whitespace in object cols
    obj_cols = df.select_dtypes(include=["object"]).columns
    for c in obj_cols:
        df[c] = df[c].astype(str).str.strip()

    return df

def main():
    os.makedirs(OUT_DIR, exist_ok=True)

    # Download raw CSV from dataset repo
    local_csv = hf_hub_download(
        repo_id=HF_DATASET_REPO,
        repo_type="dataset",
        filename="data/tourism.csv",
    )
    df = pd.read_csv(local_csv)
    df = clean(df)

    # Target must exist
    assert "ProdTaken" in df.columns, "ProdTaken target column missing!"

    train_df, test_df = train_test_split(
        df,
        test_size=TEST_SIZE,
        random_state=SEED,
        stratify=df["ProdTaken"]
    )

    train_df.to_csv(TRAIN_PATH, index=False)
    test_df.to_csv(TEST_PATH, index=False)

    # Upload processed splits back to HF dataset repo
    api = HfApi()
    api.upload_file(
     path_or_fileobj=TRAIN_PATH,
     path_in_repo="data/processed/train.csv",
     repo_id=HF_DATASET_REPO,
     repo_type="dataset",
)

    api.upload_file(
     path_or_fileobj=TEST_PATH,
     path_in_repo="data/processed/test.csv",
     repo_id=HF_DATASET_REPO,
     repo_type="dataset",
 )


    print("Prepared + uploaded train/test splits to:", HF_DATASET_REPO)

if __name__ == "__main__":
    main()