# -*- coding: utf-8 -*-
"""01_register_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15varczMUrG9sE4wz2vnBfavbNThdGCrR
"""

import os
from huggingface_hub import HfApi

HF_SPACE_REPO = os.environ["HF_SPACE_REPO"]  # e.g. username/visit-with-us-wellness-space

def main():
    api = HfApi()
    api.create_repo(
    repo_id=HF_SPACE_REPO,
    repo_type="space",
    space_sdk="docker",
    exist_ok=True
)


    api.upload_folder(
        folder_path="space",
        repo_id=HF_SPACE_REPO,
        repo_type="space",
        path_in_repo=".",
    )
    print("✅ Pushed Space files to:", HF_SPACE_REPO)

if __name__ == "__main__":
    main()